services:
  app:
    image: helium
    command: bash /start-up.sh
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: helium
    environment:
      - ENV=DEV
      - WAIT_SERVICE=database
      - POSTGRES_HOST=database
    volumes:
      - ./helium:/helium
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_DB=POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data:
